name: GitHub-Profile-3D-Contrib
on:
  schedule:
    - cron: "0 18 * * *" # Запуск каждый день в 18:00 UTC
  workflow_dispatch: # Позволяет запускать вручную

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "Generated 3D contributions" || exit 0
          git push
